# Generated by Django 4.2.3 on 2023-07-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='stream date')),
                ('time', models.TimeField()),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.videogame')),
            ],
        ),
    ]
